In [1]:
import os
os.environ["R_HOME"] = r"C:\Program Files\R\R-4.3.1"
os.environ["PATH"] = r"C:\Program Files\R\R-4.3.1\bin\x64" + ";" + os.environ["PATH"]

In [6]:
import pandas as pd
from specan3 import funcR

from rpy2.robjects.packages import STAP
from rpy2.robjects import pandas2ri

In [7]:
pandas2ri.activate()

In [8]:
audiocsv = pd.read_csv('./AudioDataR2.csv')
# audiocsv
audiorpy2 = pandas2ri.py2rpy(audiocsv)
# audiorpy2

In [9]:
specan3 = STAP(funcR, "specan3")
res = specan3.specan3(audiorpy2)
res

  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 trim_audio1.wav trim_audio10.wav trim_audio11.wav trim_audio12.wav trim_audio13.wav trim_audio14.wav trim_audio15.wav trim_audio16.wav trim_audio17.wav trim_audio18.wav trim_audio19.wav trim_audio2.wav trim_audio20.wav trim_audio21.wav trim_audio22.wav trim_audio23.wav trim_audio24.wav trim_audio25.wav trim_audio26.wav trim_audio27.wav trim_audio28.wav trim_audio29.wav trim_audio3.wav trim_audio30.wav trim_audio4.wav trim_audio5.wav trim_audio6.wav trim_audio7.wav trim_audio8.wav trim_audio9.wav 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0Measuring acoustic parameters: |                                                  | 0 % ~calculating   |++                                                | 3 % ~07s           |++++                                              | 7 % ~06s           |+++++                                             | 10% ~06s           |

<rpy2.robjects.vectors.DataFrame object at 0x00000178739206C0> [RTYPES.VECSXP]
R classes: ('data.frame',)
[StrSexpVe..., StrSexpVe..., FloatSexp..., FloatSexp..., ..., FloatSexp..., FloatSexp..., FloatSexp..., FloatSexp...]
  sound.files: <class 'numpy.ndarray'>
  array(['trim_audio1.wav', 'trim_audio10.wav', 'trim_audio11.wav',
       'trim_audio12.wav', 'trim_audio13.wav', 'trim_audio14.wav',
       'trim_audio15.wav', 'trim_audio16.wav', 'trim_audio17.wav',
       'trim_audio18.wav', 'trim_audio19.wav', 'trim_audio2.wav',
       'trim_audio20.wav', 'trim_audio21.wav', 'trim_audio22.wav',
       'trim_audio23.wav', 'trim_audio24.wav', 'trim_audio25.wav',
       'trim_audio26.wav', 'trim_audio27.wav', 'trim_audio28.wav',
       'trim_audio29.wav', 'trim_audio3.wav', 'trim_audio30.wav',
       'trim_audio4.wav', 'trim_audio5.wav', 'trim_audio6.wav',
       'trim_audio7.wav', 'trim_audio8.wav', 'trim_audio9.wav'],
      dtype='<U16')
  selec: <class 'numpy.ndarray'>
  array(['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0'], dtype='<U1')
  duration: <class 'numpy.ndarray'>
  array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])
  meanfreq: <class 'numpy.ndarray'>
  array([0.17826646, 0.16473869, 0.16918573, 0.16657434, 0.15329035,
       0.18457768, 0.17389296, 0.16695156, 0.17256824, 0.20408683,
       0.15396981, 0.18232901, 0.1586398 , 0.14841587, 0.15135881,
       0.18606196, 0.1725188 , 0.16059275, 0.17831398, 0.17492466,
       0.17037068, 0.17369058, 0.16780329, 0.18779762, 0.17612534,
       0.1932762 , 0.16740111, 0.16812908, 0.15761159, 0.16503383])
...
  median: <class 'numpy.ndarray'>
  array([0.0546875, 0.0546875, 0.0546875, 0.       , 0.       , 0.09375  ,
       0.0625   , 0.       , 0.0390625, 0.0625   , 0.       , 0.046875 ,
       0.0703125, 0.       , 0.046875 , 0.0625   , 0.       , 0.0390625,
       0.0390625, 0.046875 , 0.046875 , 0.046875 , 0.0234375, 0.078125 ,
       0.0390625, 0.0546875, 0.0546875, 0.       , 0.       , 0.046875 ])
  Q25: <class 'numpy.ndarray'>
  array([4.9453125, 0.578125 , 1.8125   , 2.140625 , 0.734375 , 2.890625 ,
       5.125    , 4.3828125, 0.84375  , 5.234375 , 6.578125 , 4.9140625,
       0.5625   , 0.9296875, 4.59375  , 0.7421875, 4.21875  , 0.8203125,
       4.6328125, 4.9921875, 0.609375 , 5.5234375, 4.       , 1.203125 ,
       4.5234375, 4.828125 , 5.0859375, 5.4609375, 4.484375 , 4.5625   ])
  Q75: <class 'numpy.ndarray'>
  array([4.890625 , 0.5234375, 1.7578125, 2.140625 , 0.734375 , 2.796875 ,
       5.0625   , 4.3828125, 0.8046875, 5.171875 , 6.578125 , 4.8671875,
       0.4921875, 0.9296875, 4.546875 , 0.6796875, 4.21875  , 0.78125  ,
       4.59375  , 4.9453125, 0.5625   , 5.4765625, 3.9765625, 1.125    ,
       4.484375 , 4.7734375, 5.03125  , 5.4609375, 4.484375 , 4.515625 ])
  IQR: <class 'numpy.ndarray'>
  array([0.13121862, 0.23677069, 0.18020202, 0.24553933, 0.23404255,
       0.12188928, 0.21296296, 0.14146816, 0.32568402, 0.10796629,
       0.1084539 , 0.19779659, 0.28659612, 0.25095493, 0.09381443,
       0.22988506, 0.14276094, 0.28136364, 0.13783609, 0.11884245,
       0.27588384, 0.12559979, 0.12002143, 0.20069444, 0.14642065,
       0.0685761 , 0.13819876, 0.20509819, 0.14119417, 0.10105379])

In [11]:
res_df = pandas2ri.rpy2py(res)
res_df

sound.files selec  duration  meanfreq        sd    median       Q25  \
1    trim_audio1.wav     0       3.0  0.178266  0.066980  0.191228  0.157855   
2   trim_audio10.wav     0       3.0  0.164739  0.071201  0.176877  0.099118   
3   trim_audio11.wav     0       3.0  0.169186  0.069028  0.177545  0.117473   
4   trim_audio12.wav     0       3.0  0.166574  0.065228  0.186555  0.104458   
5   trim_audio13.wav     0       3.0  0.153290  0.071134  0.154119  0.093220   
6   trim_audio14.wav     0       3.0  0.184578  0.062401  0.199905  0.158856   
7   trim_audio15.wav     0       3.0  0.173893  0.072854  0.196901  0.112467   
8   trim_audio16.wav     0       3.0  0.166952  0.064057  0.174875  0.128486   
9   trim_audio17.wav     0       3.0  0.172568  0.066804  0.196901  0.115805   
10  trim_audio18.wav     0       3.0  0.204087  0.057690  0.222265  0.186889   
11  trim_audio19.wav     0       3.0  0.153970  0.063912  0.167867  0.103456   
12   trim_audio2.wav     0       3.0  0.182329  0.063005  0.202574  0.147509   
13  trim_audio20.wav     0       3.0  0.158640  0.071117  0.164863  0.094779   
14  trim_audio21.wav     0       3.0  0.148416  0.071373  0.164666  0.079611   
15  trim_audio22.wav     0       3.0  0.151359  0.079150  0.167199  0.073087   
16  trim_audio23.wav     0       3.0  0.186062  0.070486  0.210250  0.139499   
17  trim_audio24.wav     0       3.0  0.172519  0.066105  0.181549  0.129154   
18  trim_audio25.wav     0       3.0  0.160593  0.067663  0.166865  0.109130   
19  trim_audio26.wav     0       3.0  0.178314  0.063468  0.201240  0.137497   
20  trim_audio27.wav     0       3.0  0.174925  0.065705  0.183886  0.140167   
21  trim_audio28.wav     0       3.0  0.170371  0.066528  0.190226  0.118808   
22  trim_audio29.wav     0       3.0  0.173691  0.057370  0.189842  0.146634   
23   trim_audio3.wav     0       3.0  0.167803  0.063581  0.180548  0.125816   
24  trim_audio30.wav     0       3.0  0.187798  0.063410  0.214255  0.162193   
25   trim_audio4.wav     0       3.0  0.176125  0.066375  0.197569  0.126150   
26   trim_audio5.wav     0       3.0  0.193276  0.062748  0.217060  0.164326   
27   trim_audio6.wav     0       3.0  0.167401  0.067144  0.175876  0.118474   
28   trim_audio7.wav     0       3.0  0.168129  0.067186  0.189225  0.113802   
29   trim_audio8.wav     0       3.0  0.157612  0.069326  0.161192  0.097449   
30   trim_audio9.wav     0       3.0  0.165034  0.084607  0.171204  0.088439   

         Q75       IQR      skew  ...  centroid  peakf   meanfun    minfun  \
1   0.228272  0.070417  2.409178  ...  0.178266    0.0  0.179330  0.048780   
2   0.224934  0.125816  0.622851  ...  0.164739    0.0  0.128828  0.015656   
3   0.226937  0.109464  1.832834  ...  0.169186    0.0  0.135699  0.015984   
4   0.215924  0.111466  1.558992  ...  0.166574    0.0  0.156617  0.030948   
5   0.220122  0.126902  0.600931  ...  0.153290    0.0  0.156471  0.017621   
6   0.233611  0.074756  1.671806  ...  0.184578    0.0  0.147444  0.020434   
7   0.236949  0.124482  2.343874  ...  0.173893    0.0  0.156805  0.016754   
8   0.210584  0.082098  2.193164  ...  0.166952    0.0  0.138322  0.017857   
9   0.222265  0.106460  2.492481  ...  0.172568    0.0  0.151419  0.015748   
10  0.244625  0.057735  2.217979  ...  0.204087    0.0  0.156084  0.016667   
11  0.193897  0.090441  2.044876  ...  0.153970    0.0  0.133793  0.016260   
12  0.226603  0.079094  1.854204  ...  0.182329    0.0  0.158350  0.016546   
13  0.213921  0.119142  1.296198  ...  0.158640    0.0  0.159833  0.028933   
14  0.209235  0.129623  1.687420  ...  0.148416    0.0  0.167907  0.015764   
15  0.216257  0.143170  1.168642  ...  0.151359    0.0  0.154401  0.017112   
16  0.243957  0.104458  1.917043  ...  0.186062    0.0  0.156701  0.015842   
17  0.218260  0.089106  1.538204  ...  0.172519    0.0  0.152105  0.020487   
18  0.216591  0.107461  0.947508  ...  0.160593    0.0  0.137275  0.016754   
19  0.218260  0.080763  2.919315  ...  0.17831

In [12]:
res_df.columns

Index(['sound.files', 'selec', 'duration', 'meanfreq', 'sd', 'median', 'Q25',
       'Q75', 'IQR', 'skew', 'kurt', 'sp.ent', 'sfm', 'mode', 'centroid',
       'peakf', 'meanfun', 'minfun', 'maxfun', 'meandom', 'mindom', 'maxdom',
       'dfrange', 'modindx'],
      dtype='object')